# -*- coding: utf-8 -*-
"""game_functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17yiw6IY3MZ0F2m-I-3V5-5GQLzw0zZJg
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile my_function.py
# import random
# 
# def fun_game(die_sides):
#   """This is a game to roll a user sided die 5 times"""
#   die_rolls=[random.randint(1,die_sides) for die in range(5)]
#   return die_rolls
# 
# def number_game():
#   secret=random.randint(1,10)
#   guess=int(input("Guess a number between 1 and 10: "))
#   if guess==secret:
#     return("You won!")
#   else:
#     return("You lost!")